[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
description = "{{project-description}}"
repository = "https://github.com/{{gh-username}}/{{project-name}}"
license = "MIT"

[dependencies]
anyhow = "1.0.104"

{% if crate_type == "bin" %}
[package.metadata.deb]
maintainer = "Nobody <devnull@wdlabs.com>"
copyright = "Nobody"
extended-description = """\
{{project-description}}"""
section = "utils"
priority = "optional"
assets = [
    ["target/release/{{project-name}}", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/{{project-name}}/README.md", "644"],
    ["LICENSE", "usr/share/doc/{{project-name}}/LICENSE", "644"],
]
{% endif %}
