name: Release

on:
  push:
    branches: [main]

{% raw  %}
concurrency: release-${{ github.ref }}
{% endraw %}

permissions:
  contents: write

{% if crate_type == "bin" %}
jobs:
  release:
    uses: uperl/action-rust-release-bin/.github/workflows/release.yml@v1
    with:
      publisher: "Graham Ollis"
{% else %}
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - id: release
        uses: uperl/action-rust-release-lib@v1
        with:
          create-release: true
{% endif %}
